### ISSUE TITLE
[USER STORY]: As an IT personal, I want to see log files in a table format, so that various data in the log can be easily analyzed. 

### ISSUE THREAD

**Issue by CeliaCaii** [mlee97/SOEN-390-Team5#39] opened 2021-02-08 05:33 UTC
# State the Related Minimal Requirement:
    [9] The system must generate logs and audit trails for the sake of debugging and accountability.

**Comment by pirasunt** [comment] 2021-02-12 15:16
Closing as this is a duplicate of #38

**Closed by pirasunt** 2021-02-12 15:16 UTC
Labels: priority: low, risk: low, story point: 3, user story
